// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: metrics/metric_export.proto

package metricspb

import (
	monitoringpb "cloud.google.com/go/monitoring/apiv3/v2/monitoringpb"
	metric "google.golang.org/genproto/googleapis/api/metric"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricDescriptorExport wraps the exported metric descriptors
type MetricDescriptorExport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Export metadata
	Metadata *ExportMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// List of metric descriptors
	Descriptors   []*MetricDescriptorSnapshot `protobuf:"bytes,2,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDescriptorExport) Reset() {
	*x = MetricDescriptorExport{}
	mi := &file_metrics_metric_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDescriptorExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDescriptorExport) ProtoMessage() {}

func (x *MetricDescriptorExport) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDescriptorExport.ProtoReflect.Descriptor instead.
func (*MetricDescriptorExport) Descriptor() ([]byte, []int) {
	return file_metrics_metric_export_proto_rawDescGZIP(), []int{0}
}

func (x *MetricDescriptorExport) GetMetadata() *ExportMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MetricDescriptorExport) GetDescriptors() []*MetricDescriptorSnapshot {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

// Export metadata
type ExportMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExportTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=export_time,json=exportTime,proto3" json:"export_time,omitempty"`
	ExporterVersion string                 `protobuf:"bytes,3,opt,name=exporter_version,json=exporterVersion,proto3" json:"exporter_version,omitempty"`
	TotalCount      int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExportMetadata) Reset() {
	*x = ExportMetadata{}
	mi := &file_metrics_metric_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetadata) ProtoMessage() {}

func (x *ExportMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetadata.ProtoReflect.Descriptor instead.
func (*ExportMetadata) Descriptor() ([]byte, []int) {
	return file_metrics_metric_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportMetadata) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExportMetadata) GetExportTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExportTime
	}
	return nil
}

func (x *ExportMetadata) GetExporterVersion() string {
	if x != nil {
		return x.ExporterVersion
	}
	return ""
}

func (x *ExportMetadata) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Snapshot of a metric descriptor
type MetricDescriptorSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original metric descriptor from API
	Descriptor_ *metric.MetricDescriptor `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	// Additional extraction metadata
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDescriptorSnapshot) Reset() {
	*x = MetricDescriptorSnapshot{}
	mi := &file_metrics_metric_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDescriptorSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDescriptorSnapshot) ProtoMessage() {}

func (x *MetricDescriptorSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDescriptorSnapshot.ProtoReflect.Descriptor instead.
func (*MetricDescriptorSnapshot) Descriptor() ([]byte, []int) {
	return file_metrics_metric_export_proto_rawDescGZIP(), []int{2}
}

func (x *MetricDescriptorSnapshot) GetDescriptor_() *metric.MetricDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *MetricDescriptorSnapshot) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

// Time series export for a single metric
type TimeSeriesExport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Export metadata
	Metadata *ExportMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Metric type identifier
	MetricType string `protobuf:"bytes,2,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	// Query time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Time series data from Cloud Monitoring API
	TimeSeries    []*monitoringpb.TimeSeries `protobuf:"bytes,5,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesExport) Reset() {
	*x = TimeSeriesExport{}
	mi := &file_metrics_metric_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesExport) ProtoMessage() {}

func (x *TimeSeriesExport) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesExport.ProtoReflect.Descriptor instead.
func (*TimeSeriesExport) Descriptor() ([]byte, []int) {
	return file_metrics_metric_export_proto_rawDescGZIP(), []int{3}
}

func (x *TimeSeriesExport) GetMetadata() *ExportMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TimeSeriesExport) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *TimeSeriesExport) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TimeSeriesExport) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TimeSeriesExport) GetTimeSeries() []*monitoringpb.TimeSeries {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

var File_metrics_metric_export_proto protoreflect.FileDescriptor

const file_metrics_metric_export_proto_rawDesc = "" +
	"\n" +
	"\x1bmetrics/metric_export.proto\x12\x11metrics.export.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/api/metric.proto\x1a!google/monitoring/v3/metric.proto\"\xa6\x01\n" +
	"\x16MetricDescriptorExport\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.metrics.export.v1.ExportMetadataR\bmetadata\x12M\n" +
	"\vdescriptors\x18\x02 \x03(\v2+.metrics.export.v1.MetricDescriptorSnapshotR\vdescriptors\"\xb8\x01\n" +
	"\x0eExportMetadata\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12;\n" +
	"\vexport_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"exportTime\x12)\n" +
	"\x10exporter_version\x18\x03 \x01(\tR\x0fexporterVersion\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"\x95\x01\n" +
	"\x18MetricDescriptorSnapshot\x12<\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2\x1c.google.api.MetricDescriptorR\n" +
	"descriptor\x12;\n" +
	"\vcaptured_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\xa7\x02\n" +
	"\x10TimeSeriesExport\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.metrics.export.v1.ExportMetadataR\bmetadata\x12\x1f\n" +
	"\vmetric_type\x18\x02 \x01(\tR\n" +
	"metricType\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12A\n" +
	"\vtime_series\x18\x05 \x03(\v2 .google.monitoring.v3.TimeSeriesR\n" +
	"timeSeriesB<Z:github.com/devil-mice-labs/metricbucketferry/pkg/metricspbb\x06proto3"

var (
	file_metrics_metric_export_proto_rawDescOnce sync.Once
	file_metrics_metric_export_proto_rawDescData []byte
)

func file_metrics_metric_export_proto_rawDescGZIP() []byte {
	file_metrics_metric_export_proto_rawDescOnce.Do(func() {
		file_metrics_metric_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_metric_export_proto_rawDesc), len(file_metrics_metric_export_proto_rawDesc)))
	})
	return file_metrics_metric_export_proto_rawDescData
}

var file_metrics_metric_export_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metrics_metric_export_proto_goTypes = []any{
	(*MetricDescriptorExport)(nil),   // 0: metrics.export.v1.MetricDescriptorExport
	(*ExportMetadata)(nil),           // 1: metrics.export.v1.ExportMetadata
	(*MetricDescriptorSnapshot)(nil), // 2: metrics.export.v1.MetricDescriptorSnapshot
	(*TimeSeriesExport)(nil),         // 3: metrics.export.v1.TimeSeriesExport
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*metric.MetricDescriptor)(nil),  // 5: google.api.MetricDescriptor
	(*monitoringpb.TimeSeries)(nil),  // 6: google.monitoring.v3.TimeSeries
}
var file_metrics_metric_export_proto_depIdxs = []int32{
	1, // 0: metrics.export.v1.MetricDescriptorExport.metadata:type_name -> metrics.export.v1.ExportMetadata
	2, // 1: metrics.export.v1.MetricDescriptorExport.descriptors:type_name -> metrics.export.v1.MetricDescriptorSnapshot
	4, // 2: metrics.export.v1.ExportMetadata.export_time:type_name -> google.protobuf.Timestamp
	5, // 3: metrics.export.v1.MetricDescriptorSnapshot.descriptor:type_name -> google.api.MetricDescriptor
	4, // 4: metrics.export.v1.MetricDescriptorSnapshot.captured_at:type_name -> google.protobuf.Timestamp
	1, // 5: metrics.export.v1.TimeSeriesExport.metadata:type_name -> metrics.export.v1.ExportMetadata
	4, // 6: metrics.export.v1.TimeSeriesExport.start_time:type_name -> google.protobuf.Timestamp
	4, // 7: metrics.export.v1.TimeSeriesExport.end_time:type_name -> google.protobuf.Timestamp
	6, // 8: metrics.export.v1.TimeSeriesExport.time_series:type_name -> google.monitoring.v3.TimeSeries
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_metrics_metric_export_proto_init() }
func file_metrics_metric_export_proto_init() {
	if File_metrics_metric_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_metric_export_proto_rawDesc), len(file_metrics_metric_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_metric_export_proto_goTypes,
		DependencyIndexes: file_metrics_metric_export_proto_depIdxs,
		MessageInfos:      file_metrics_metric_export_proto_msgTypes,
	}.Build()
	File_metrics_metric_export_proto = out.File
	file_metrics_metric_export_proto_goTypes = nil
	file_metrics_metric_export_proto_depIdxs = nil
}
